# Default values for Technitium.

# Name of the DNS Server


# Technitium Specific Configurations
config:
  dnsDomain: "dns-server"
  # Leave empty to automatically generate a random 16-character password
  adminPassword: ""
  # preferIpv6: false
  # recursion: AllowOnlyForPrivateNetworks
  # Example ACL: "192.168.10.0/24, !192.168.10.2"
  # recursionAcl: ""
  # enableBlocking: true
  # forwarders: "1.1.1.1, 8.8.8.8"
  # forwarderProtocol: "Udp"
  # logLocalTime: true

image:
  repository: technitium/dns-server
  pullPolicy: IfNotPresent
  # tag: "14.3.0"

service: {}
  # type: ClusterIP

persistence: {}
  # accessMode: ReadWriteOnce
  # size: 2Gi
  # storageClass:

ingress:
  enabled: true
  hosts:
    - host: admin.technitium.local
      paths:
        - path: /
          pathType: Prefix
          port: 5380
  tls: []
  #  - secretName: technitium-tls
  #    hosts:
  #      -  admin.technitium.local