{{/*
MIT License

Copyright (c) 2026 Shane

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "technitium.fullname" . }}
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "technitium.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "technitium.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "technitium.serviceAccountName" . }}
      containers:
        - name: technitium-dns-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.ports.webHttp | default 5380 }}
              name: web-ui-http
              protocol: TCP
                    {{- if .Values.config.webServiceEnableHttps }}
            - containerPort: {{ index .Values "ports" "webHttps" | default 53443 }}
              name: web-ui-https
              protocol: TCP
                    {{- end }}
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
                  {{- if index .Values "ports" "doq" "enabled" }}
            - containerPort: 853
              name: doq-udp
              protocol: UDP
                  {{- end }}
                  {{- if index .Values "ports" "dot" "enabled" }}
            - containerPort: 853
              name: dot-tcp
              protocol: TCP
                  {{- end }}
                  {{- if index .Values "ports" "doh3" "enabled" }}
            - containerPort: 443
              name: doh3-udp
              protocol: UDP
                  {{- end }}
                  {{- if index .Values "ports" "doh" "enabled" }}
            - containerPort: 443
              name: doh-tcp
              protocol: TCP
                  {{- end }}
                  {{- if index .Values "ports" "dohHttpProxy" "enabled" }}
            - containerPort: 80
              name: doh-proxy-http
              protocol: TCP
                  {{- end }}
                  {{- if index .Values "ports" "dohProxy" "enabled" }}
            - containerPort: 8053
              name: doh-proxy
              protocol: TCP
                  {{- end }}
                  {{- if index .Values "ports" "dhcp" "enabled" }}
            - containerPort: 67
              name: dhcp
              protocol: UDP
                  {{- end }}
          livenessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: dns-tcp
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: DNS_SERVER_DOMAIN
              value: {{ required "A valid .Values.config.dnsDomain is required!" .Values.config.dnsDomain | quote }}
            - name: DNS_SERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "technitium.fullname" . }}-admin
                  key: password
                  {{- if .Values.config.preferIpv6 }}
            - name: DNS_SERVER_PREFER_IPV6
              value: {{ .Values.config.preferIpv6 | quote }}
                  {{- end }}
                  {{- if .Values.config.webServiceLocalAddresses }}
            - name: DNS_SERVER_WEB_SERVICE_LOCAL_ADDRESSES
              value: {{ .Values.config.webServiceLocalAddresses | quote }}
                  {{- end }}
            - name: DNS_SERVER_WEB_SERVICE_HTTP_PORT
              value: {{ .Values.ports.webHttp | default 5380 | quote }}
                  {{- if .Values.config.webServiceEnableHttps }}
            - name: DNS_SERVER_WEB_SERVICE_HTTPS_PORT
              value: {{ index .Values "ports" "webHttps" | default 53443 | quote }}
                  {{- end }}
                  {{- if .Values.config.webServiceEnableHttps }}
            - name: DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS
              value: {{ .Values.config.webServiceEnableHttps | quote }}
                  {{- end }}
                  {{- if .Values.config.webServiceUseSelfSignedCert }}
            - name: DNS_SERVER_WEB_SERVICE_USE_SELF_SIGNED_CERT
              value: {{ .Values.config.webServiceUseSelfSignedCert | quote }}
                  {{- end }}
                  {{- if .Values.config.webServiceEnableHttps }}
            - name: DNS_SERVER_WEB_SERVICE_TLS_CERTIFICATE_PATH
              value: {{ .Values.config.webServiceTlsCertificatePath | quote }}
                  {{- end }}
                  {{- if .Values.config.webServiceTlsCertificatePassword }}
            - name: DNS_SERVER_WEB_SERVICE_TLS_CERTIFICATE_PASSWORD
              value: {{ .Values.config.webServiceTlsCertificatePassword | quote }}
                  {{- end }}
                  {{- if .Values.config.webServiceHttpToTlsRedirect }}
            - name: DNS_SERVER_WEB_SERVICE_HTTP_TO_TLS_REDIRECT
              value: {{ .Values.config.webServiceHttpToTlsRedirect | quote }}
                  {{- end }}
                  {{- if .Values.config.optionalProtocolDnsOverHttp }}
            - name: DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP
              value: {{ .Values.config.optionalProtocolDnsOverHttp | quote }}
                  {{- end }}
                  {{- if .Values.config.recursion }}
            - name: DNS_SERVER_RECURSION
              value: {{ .Values.config.recursion | quote }}
                  {{- end }}
                  {{- if .Values.config.recursionAcl }}
            - name: DNS_SERVER_RECURSION_NETWORK_ACL
              value: {{ .Values.config.recursionAcl | quote }}
                  {{- end }}
                  {{- if .Values.config.recursionDeniedNetworks }}
            - name: DNS_SERVER_RECURSION_DENIED_NETWORKS
              value: {{ .Values.config.recursionDeniedNetworks | quote }}
                  {{- end }}
                  {{- if .Values.config.recursionAllowedNetworks }}
            - name: DNS_SERVER_RECURSION_ALLOWED_NETWORKS
              value: {{ .Values.config.recursionAllowedNetworks | quote }}
                  {{- end }}
                  {{- if .Values.config.enableBlocking }}
            - name: DNS_SERVER_ENABLE_BLOCKING
              value: {{ .Values.config.enableBlocking | quote }}
                  {{- end }}
                  {{- if .Values.config.allowTxtBlockingReport }}
            - name: DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT
              value: {{ .Values.config.allowTxtBlockingReport | quote }}
                  {{- end }}
                  {{- if .Values.config.blockListUrls }}
            - name: DNS_SERVER_BLOCK_LIST_URLS
              value: {{ .Values.config.blockListUrls | quote }}
                  {{- end }}
                  {{- if .Values.config.forwarders }}
            - name: DNS_SERVER_FORWARDERS
              value: {{ .Values.config.forwarders | quote }}
                  {{- end }}
                  {{- if .Values.config.forwarderProtocol }}
            - name: DNS_SERVER_FORWARDER_PROTOCOL
              value: {{ .Values.config.forwarderProtocol | quote }}
                  {{- end }}
                  {{- if .Values.config.logLocalTime }}
            - name: DNS_SERVER_LOG_USING_LOCAL_TIME
              value: {{ .Values.config.logLocalTime | quote }}
                  {{- end }}
          volumeMounts:
            - name: config-storage
              mountPath: /etc/dns
      volumes:
        - name: config-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-config-pvc" (include "technitium.fullname" .)) }}