apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-config-pvc
  labels:
    {{ include "technitium.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ (index .Values "persistence" | default dict).accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage:  {{ (index .Values "persistence" | default dict).size | default "2Gi" }}
  {{ if .Values.persistence.storageClass }}
  storageClassName: {{ (index .Values "persistence" | default dict).storageClass | default "" }}
  {{ end }}