apiVersion: v1
kind: Secret
metadata:
  name: {{ include "technitium.fullname" . }}-admin
  labels:
    {{- include "technitium.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s-admin" (include "technitium.fullname" .))) -}}
  {{- if $secret }}
  password: {{ index $secret.data "password" }}
  {{- else if .Values.config.adminPassword }}
  password: {{ .Values.config.adminPassword | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}