apiVersion: v1
kind: Service
metadata:
  name: {{ include "technitium.fullname" . }}
  labels:
    {{ include "technitium.labels" . | nindent 4 }}
spec:
  type: {{ (index .Values "service" | default dict).type | default "LoadBalancer" }}
  selector:
    {{ include "technitium.selectorLabels" . | nindent 4 }}
  ports:
    - name: web-ui
      port: 5380
      targetPort: 5380
      protocol: TCP
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53