name: GoLic
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - main
jobs:
  GoLic:
    name: GoLic
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GoLic
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go install github.com/Bugs5382/golic@v0.1.0
          golic inject -t mit -c "2026 Shane" -d -x
